# Generated by Django 5.2.17 on 2026-09-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA/SMK'), ('d3', 'D3'), ('s1', 'S1'), ('s2', 'S2')], default='s1', max_length=10)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
    ]
